/*

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license ( the "Software" ) to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/
module derelict.gles.functions2;

private {
    import derelict.gles.types2;
}

extern( System ) nothrow {
    alias void function( GLenum ) da_glActiveTexture;
    alias void function( GLuint, GLuint ) da_glAttachShader;
    alias void function( GLuint, GLuint, const GLchar* ) da_glBindAttribLocation;
    alias void function( GLenum, GLuint ) da_glBindBuffer;
    alias void function( GLenum, GLuint ) da_glBindFramebuffer;
    alias void function( GLenum, GLuint ) da_glBindRenderbuffer;
    alias void function( GLenum, GLuint ) da_glBindTexture;
    alias void function( GLfloat, GLfloat, GLfloat, GLfloat ) da_glBlendColor;
    alias void function( GLenum ) da_glBlendEquation;
    alias void function( GLenum, GLenum ) da_glBlendEquationSeparate;
    alias void function( GLenum, GLenum ) da_glBlendFunc;
    alias void function( GLenum, GLenum dfactorRGB, GLenum, GLenum ) da_glBlendFuncSeparate;
    alias void function( GLenum, GLsizeiptr, const void*, GLenum ) da_glBufferData;
    alias void function( GLenum, GLintptr, GLsizeiptr, const void* ) da_glBufferSubData;
    alias GLenum function( GLenum ) da_glCheckFramebufferStatus;
    alias void function( GLbitfield ) da_glClear;
    alias void function( GLfloat, GLfloat, GLfloat, GLfloat ) da_glClearColor;
    alias void function( GLfloat ) da_glClearDepthf;
    alias void function( GLint ) da_glClearStencil;
    alias void function( GLboolean, GLboolean, GLboolean, GLboolean ) da_glColorMask;
    alias void function( GLuint ) da_glCompileShader;
    alias void function( GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLsizei, const void* ) da_glCompressedTexImage2D;
    alias void function( GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, const void* ) da_glCompressedTexSubImage2D;
    alias void function( GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLsizei, GLint ) da_glCopyTexImage2D;
    alias void function( GLenum, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei ) da_glCopyTexSubImage2D;
    alias GLuint function(  ) da_glCreateProgram;
    alias GLuint function( GLenum ) da_glCreateShader;
    alias void function( GLenum ) da_glCullFace;
    alias void function( GLsizei, const GLuint* ) da_glDeleteBuffers;
    alias void function( GLsizei, const GLuint* ) da_glDeleteFramebuffers;
    alias void function( GLuint ) da_glDeleteProgram;
    alias void function( GLsizei, const GLuint* ) da_glDeleteRenderbuffers;
    alias void function( GLuint ) da_glDeleteShader;
    alias void function( GLsizei, const GLuint* ) da_glDeleteTextures;
    alias void function( GLenum ) da_glDepthFunc;
    alias void function( GLboolean ) da_glDepthMask;
    alias void function( GLfloat, GLfloat ) da_glDepthRangef;
    alias void function( GLuint, GLuint ) da_glDetachShader;
    alias void function( GLenum ) da_glDisable;
    alias void function( GLuint ) da_glDisableVertexAttribArray;
    alias void function( GLenum, GLint, GLsizei ) da_glDrawArrays;
    alias void function( GLenum, GLsizei, GLenum, const void* ) da_glDrawElements;
    alias void function( GLenum ) da_glEnable;
    alias void function( GLuint ) da_glEnableVertexAttribArray;
    alias void function(  ) da_glFinish;
    alias void function(  ) da_glFlush;
    alias void function( GLenum, GLenum, GLenum, GLuint ) da_glFramebufferRenderbuffer;
    alias void function( GLenum, GLenum, GLenum, GLuint, GLint ) da_glFramebufferTexture2D;
    alias void function( GLenum ) da_glFrontFace;
    alias void function( GLsizei, GLuint* ) da_glGenBuffers;
    alias void function( GLenum ) da_glGenerateMipmap;
    alias void function( GLsizei, GLuint* ) da_glGenFramebuffers;
    alias void function( GLsizei, GLuint* ) da_glGenRenderbuffers;
    alias void function( GLsizei, GLuint* ) da_glGenTextures;
    alias void function( GLuint, GLuint, GLsizei, GLsizei*, GLint*, GLenum*, GLchar* ) da_glGetActiveAttrib;
    alias void function( GLuint, GLuint, GLsizei, GLsizei*, GLint*, GLenum*, GLchar* ) da_glGetActiveUniform;
    alias void function( GLuint, GLsizei maxCount, GLsizei*, GLuint* ) da_glGetAttachedShaders;
    alias GLint function( GLuint, const GLchar* ) da_glGetAttribLocation;
    alias void function( GLenum, GLboolean* ) da_glGetBooleanv;
    alias void function( GLenum, GLenum, GLint* ) da_glGetBufferParameteriv;
    alias GLenum function(  ) da_glGetError;
    alias void function( GLenum, GLfloat* ) da_glGetFloatv;
    alias void function( GLenum, GLenum, GLenum, GLint* ) da_glGetFramebufferAttachmentParameteriv;
    alias void function( GLenum, GLint* ) da_glGetIntegerv;
    alias void function( GLuint, GLenum, GLint* ) da_glGetProgramiv;
    alias void function( GLuint, GLsizei, GLsizei*, GLchar*infoLog ) da_glGetProgramInfoLog;
    alias void function( GLenum, GLenum, GLint* ) da_glGetRenderbufferParameteriv;
    alias void function( GLuint, GLenum, GLint* ) da_glGetShaderiv;
    alias void function( GLuint, GLsizei, GLsizei*, GLchar*infoLog ) da_glGetShaderInfoLog;
    alias void function( GLenum, GLenum, GLint*, GLint* ) da_glGetShaderPrecisionFormat;
    alias void function( GLuint, GLsizei, GLsizei*, GLchar* ) da_glGetShaderSource;
    alias const GLubyte* function( GLenum ) da_glGetString;
    alias void function( GLenum, GLenum, GLfloat* ) da_glGetTexParameterfv;
    alias void function( GLenum, GLenum, GLint* ) da_glGetTexParameteriv;
    alias void function( GLuint, GLint, GLfloat* ) da_glGetUniformfv;
    alias void function( GLuint, GLint, GLint* ) da_glGetUniformiv;
    alias GLint function( GLuint, const GLchar* ) da_glGetUniformLocation;
    alias void function( GLuint, GLenum, GLfloat* ) da_glGetVertexAttribfv;
    alias void function( GLuint, GLenum, GLint* ) da_glGetVertexAttribiv;
    alias void function( GLuint, GLenum, void** ) da_glGetVertexAttribPointerv;
    alias void function( GLenum, GLenum ) da_glHint;
    alias GLboolean function( GLuint ) da_glIsBuffer;
    alias GLboolean function( GLenum ) da_glIsEnabled;
    alias GLboolean function( GLuint ) da_glIsFramebuffer;
    alias GLboolean function( GLuint ) da_glIsProgram;
    alias GLboolean function( GLuint ) da_glIsRenderbuffer;
    alias GLboolean function( GLuint ) da_glIsShader;
    alias GLboolean function( GLuint ) da_glIsTexture;
    alias void function( GLfloat ) da_glLineWidth;
    alias void function( GLuint ) da_glLinkProgram;
    alias void function( GLenum, GLint ) da_glPixelStorei;
    alias void function( GLfloat, GLfloat ) da_glPolygonOffset;
    alias void function( GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, void* ) da_glReadPixels;
    alias void function(  ) da_glReleaseShaderCompiler;
    alias void function( GLenum, GLenum, GLsizei, GLsizei ) da_glRenderbufferStorage;
    alias void function( GLfloat, GLboolean ) da_glSampleCoverage;
    alias void function( GLint, GLint, GLsizei, GLsizei ) da_glScissor;
    alias void function( GLsizei, const GLuint*, GLenum, const void*, GLsizei ) da_glShaderBinary;
    alias void function( GLuint, GLsizei, const(const(GLchar)*)*, const GLint* ) da_glShaderSource;
    alias void function( GLenum, GLint, GLuint ) da_glStencilFunc;
    alias void function( GLenum, GLenum, GLint, GLuint ) da_glStencilFuncSeparate;
    alias void function( GLuint ) da_glStencilMask;
    alias void function( GLenum, GLuint ) da_glStencilMaskSeparate;
    alias void function( GLenum, GLenum, GLenum ) da_glStencilOp;
    alias void function( GLenum, GLenum, GLenum, GLenum ) da_glStencilOpSeparate;
    alias void function( GLenum, GLint, GLint, GLsizei, GLsizei, GLint, GLenum, GLenum, const void* ) da_glTexImage2D;
    alias void function( GLenum, GLenum, GLfloat ) da_glTexParameterf;
    alias void function( GLenum, GLenum, const GLfloat* ) da_glTexParameterfv;
    alias void function( GLenum, GLenum, GLint ) da_glTexParameteri;
    alias void function( GLenum, GLenum, const GLint* ) da_glTexParameteriv;
    alias void function( GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, const void* ) da_glTexSubImage2D;
    alias void function( GLint, GLfloat v0 ) da_glUniform1f;
    alias void function( GLint, GLsizei, const GLfloat* ) da_glUniform1fv;
    alias void function( GLint, GLint v0 ) da_glUniform1i;
    alias void function( GLint, GLsizei, const GLint* ) da_glUniform1iv;
    alias void function( GLint, GLfloat v0, GLfloat v1 ) da_glUniform2f;
    alias void function( GLint, GLsizei, const GLfloat* ) da_glUniform2fv;
    alias void function( GLint, GLint v0, GLint v1 ) da_glUniform2i;
    alias void function( GLint, GLsizei, const GLint* ) da_glUniform2iv;
    alias void function( GLint, GLfloat v0, GLfloat v1, GLfloat v2 ) da_glUniform3f;
    alias void function( GLint, GLsizei, const GLfloat* ) da_glUniform3fv;
    alias void function( GLint, GLint v0, GLint v1, GLint v2 ) da_glUniform3i;
    alias void function( GLint, GLsizei, const GLint* ) da_glUniform3iv;
    alias void function( GLint, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3 ) da_glUniform4f;
    alias void function( GLint, GLsizei, const GLfloat* ) da_glUniform4fv;
    alias void function( GLint, GLint v0, GLint v1, GLint v2, GLint v3 ) da_glUniform4i;
    alias void function( GLint, GLsizei, const GLint* ) da_glUniform4iv;
    alias void function( GLint, GLsizei, GLboolean, const GLfloat* ) da_glUniformMatrix2fv;
    alias void function( GLint, GLsizei, GLboolean, const GLfloat* ) da_glUniformMatrix3fv;
    alias void function( GLint, GLsizei, GLboolean, const GLfloat* ) da_glUniformMatrix4fv;
    alias void function( GLuint ) da_glUseProgram;
    alias void function( GLuint ) da_glValidateProgram;
    alias void function( GLuint, GLfloat ) da_glVertexAttrib1f;
    alias void function( GLuint, const GLfloat* ) da_glVertexAttrib1fv;
    alias void function( GLuint, GLfloat, GLfloat ) da_glVertexAttrib2f;
    alias void function( GLuint, const GLfloat* ) da_glVertexAttrib2fv;
    alias void function( GLuint, GLfloat, GLfloat, GLfloat ) da_glVertexAttrib3f;
    alias void function( GLuint, const GLfloat* ) da_glVertexAttrib3fv;
    alias void function( GLuint, GLfloat, GLfloat, GLfloat, GLfloat ) da_glVertexAttrib4f;
    alias void function( GLuint, const GLfloat* ) da_glVertexAttrib4fv;
    alias void function( GLuint, GLint, GLenum, GLboolean, GLsizei, const void* ) da_glVertexAttribPointer;
    alias void function( GLint, GLint, GLsizei, GLsizei ) da_glViewport;
}

__gshared {
    da_glActiveTexture glActiveTexture;
    da_glAttachShader glAttachShader;
    da_glBindAttribLocation glBindAttribLocation;
    da_glBindBuffer glBindBuffer;
    da_glBindFramebuffer glBindFramebuffer;
    da_glBindRenderbuffer glBindRenderbuffer;
    da_glBindTexture glBindTexture;
    da_glBlendColor glBlendColor;
    da_glBlendEquation glBlendEquation;
    da_glBlendEquationSeparate glBlendEquationSeparate;
    da_glBlendFunc glBlendFunc;
    da_glBlendFuncSeparate glBlendFuncSeparate;
    da_glBufferData glBufferData;
    da_glBufferSubData glBufferSubData;
    da_glCheckFramebufferStatus glCheckFramebufferStatus;
    da_glClear glClear;
    da_glClearColor glClearColor;
    da_glClearDepthf glClearDepthf;
    da_glClearStencil glClearStencil;
    da_glColorMask glColorMask;
    da_glCompileShader glCompileShader;
    da_glCompressedTexImage2D glCompressedTexImage2D;
    da_glCompressedTexSubImage2D glCompressedTexSubImage2D;
    da_glCopyTexImage2D glCopyTexImage2D;
    da_glCopyTexSubImage2D glCopyTexSubImage2D;
    da_glCreateProgram glCreateProgram;
    da_glCreateShader glCreateShader;
    da_glCullFace glCullFace;
    da_glDeleteBuffers glDeleteBuffers;
    da_glDeleteFramebuffers glDeleteFramebuffers;
    da_glDeleteProgram glDeleteProgram;
    da_glDeleteRenderbuffers glDeleteRenderbuffers;
    da_glDeleteShader glDeleteShader;
    da_glDeleteTextures glDeleteTextures;
    da_glDepthFunc glDepthFunc;
    da_glDepthMask glDepthMask;
    da_glDepthRangef glDepthRangef;
    da_glDetachShader glDetachShader;
    da_glDisable glDisable;
    da_glDisableVertexAttribArray glDisableVertexAttribArray;
    da_glDrawArrays glDrawArrays;
    da_glDrawElements glDrawElements;
    da_glEnable glEnable;
    da_glEnableVertexAttribArray glEnableVertexAttribArray;
    da_glFinish glFinish;
    da_glFlush glFlush;
    da_glFramebufferRenderbuffer glFramebufferRenderbuffer;
    da_glFramebufferTexture2D glFramebufferTexture2D;
    da_glFrontFace glFrontFace;
    da_glGenBuffers glGenBuffers;
    da_glGenerateMipmap glGenerateMipmap;
    da_glGenFramebuffers glGenFramebuffers;
    da_glGenRenderbuffers glGenRenderbuffers;
    da_glGenTextures glGenTextures;
    da_glGetActiveAttrib glGetActiveAttrib;
    da_glGetActiveUniform glGetActiveUniform;
    da_glGetAttachedShaders glGetAttachedShaders;
    da_glGetAttribLocation glGetAttribLocation;
    da_glGetBooleanv glGetBooleanv;
    da_glGetBufferParameteriv glGetBufferParameteriv;
    da_glGetError glGetError;
    da_glGetFloatv glGetFloatv;
    da_glGetFramebufferAttachmentParameteriv glGetFramebufferAttachmentParameteriv;
    da_glGetIntegerv glGetIntegerv;
    da_glGetProgramiv glGetProgramiv;
    da_glGetProgramInfoLog glGetProgramInfoLog;
    da_glGetRenderbufferParameteriv glGetRenderbufferParameteriv;
    da_glGetShaderiv glGetShaderiv;
    da_glGetShaderInfoLog glGetShaderInfoLog;
    da_glGetShaderPrecisionFormat glGetShaderPrecisionFormat;
    da_glGetShaderSource glGetShaderSource;
    da_glGetString glGetString;
    da_glGetTexParameterfv glGetTexParameterfv;
    da_glGetTexParameteriv glGetTexParameteriv;
    da_glGetUniformfv glGetUniformfv;
    da_glGetUniformiv glGetUniformiv;
    da_glGetUniformLocation glGetUniformLocation;
    da_glGetVertexAttribfv glGetVertexAttribfv;
    da_glGetVertexAttribiv glGetVertexAttribiv;
    da_glGetVertexAttribPointerv glGetVertexAttribPointerv;
    da_glHint glHint;
    da_glIsBuffer glIsBuffer;
    da_glIsEnabled glIsEnabled;
    da_glIsFramebuffer glIsFramebuffer;
    da_glIsProgram glIsProgram;
    da_glIsRenderbuffer glIsRenderbuffer;
    da_glIsShader glIsShader;
    da_glIsTexture glIsTexture;
    da_glLineWidth glLineWidth;
    da_glLinkProgram glLinkProgram;
    da_glPixelStorei glPixelStorei;
    da_glPolygonOffset glPolygonOffset;
    da_glReadPixels glReadPixels;
    da_glReleaseShaderCompiler glReleaseShaderCompiler;
    da_glRenderbufferStorage glRenderbufferStorage;
    da_glSampleCoverage glSampleCoverage;
    da_glScissor glScissor;
    da_glShaderBinary glShaderBinary;
    da_glShaderSource glShaderSource;
    da_glStencilFunc glStencilFunc;
    da_glStencilFuncSeparate glStencilFuncSeparate;
    da_glStencilMask glStencilMask;
    da_glStencilMaskSeparate glStencilMaskSeparate;
    da_glStencilOp glStencilOp;
    da_glStencilOpSeparate glStencilOpSeparate;
    da_glTexImage2D glTexImage2D;
    da_glTexParameterf glTexParameterf;
    da_glTexParameterfv glTexParameterfv;
    da_glTexParameteri glTexParameteri;
    da_glTexParameteriv glTexParameteriv;
    da_glTexSubImage2D glTexSubImage2D;
    da_glUniform1f glUniform1f;
    da_glUniform1fv glUniform1fv;
    da_glUniform1i glUniform1i;
    da_glUniform1iv glUniform1iv;
    da_glUniform2f glUniform2f;
    da_glUniform2fv glUniform2fv;
    da_glUniform2i glUniform2i;
    da_glUniform2iv glUniform2iv;
    da_glUniform3f glUniform3f;
    da_glUniform3fv glUniform3fv;
    da_glUniform3i glUniform3i;
    da_glUniform3iv glUniform3iv;
    da_glUniform4f glUniform4f;
    da_glUniform4fv glUniform4fv;
    da_glUniform4i glUniform4i;
    da_glUniform4iv glUniform4iv;
    da_glUniformMatrix2fv glUniformMatrix2fv;
    da_glUniformMatrix3fv glUniformMatrix3fv;
    da_glUniformMatrix4fv glUniformMatrix4fv;
    da_glUseProgram glUseProgram;
    da_glValidateProgram glValidateProgram;
    da_glVertexAttrib1f glVertexAttrib1f;
    da_glVertexAttrib1fv glVertexAttrib1fv;
    da_glVertexAttrib2f glVertexAttrib2f;
    da_glVertexAttrib2fv glVertexAttrib2fv;
    da_glVertexAttrib3f glVertexAttrib3f;
    da_glVertexAttrib3fv glVertexAttrib3fv;
    da_glVertexAttrib4f glVertexAttrib4f;
    da_glVertexAttrib4fv glVertexAttrib4fv;
    da_glVertexAttribPointer glVertexAttribPointer;
    da_glViewport glViewport;
}
